services:

  listing-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: listingDB
    ports:
      - "5432:5432"
    volumes:
      - listing-pg-data:/var/lib/postgresql/data
      - ./sql/listing-db.sql:/docker-entrypoint-initdb.d/listing-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d listingDB"]
      interval: 3s
      timeout: 3s
      retries: 5

  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderDB
    ports:
      - "5434:5432"
    volumes:
      - order-pg-data:/var/lib/postgresql/data
      - ./sql/order-db.sql:/docker-entrypoint-initdb.d/order-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orderDB"]
      interval: 3s
      timeout: 3s
      retries: 5

  payment-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentDB
    ports:
      - "5436:5432"
    volumes:
      - payment-pg-data:/var/lib/postgresql/data
      - ./sql/payment-db.sql:/docker-entrypoint-initdb.d/payment-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d paymentDB"]
      interval: 3s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Сервисы
  listing-service:
    build:
      context: ./services/listing-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      listing-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:8080"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:8080"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      payment-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:8080"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      order-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      listing-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped


volumes:
  listing-pg-data:
  order-pg-data:
  payment-pg-data:
  rabbitmq_data: