services:
#  postgres 1
#  postgres 2
#  postgres 3
#  kafka
#  network
#

  listing-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: listingDB
    ports:
      - "5432:5432"
    volumes:
      - listing-pg-data:/var/lib/postgresql/data
#      - ./sql/listing-db.sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5

  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderDB
    ports:
      - "5434:5432"
    volumes:
      - order-pg-data:/var/lib/postgresql/data
      - ./sql/order-db.sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  listing-pg-data:
  order-pg-data: