syntax = "proto3";

package order.v1;

import "google/protobuf/empty.proto";
import "listing/v1/listing.proto";

option go_package = "simple-marketplace-project/gen/order/v1;orderv1";

service OrderService{
  rpc GetOrderProducts(OrderRequest) returns(OrderResponse);
  rpc GetOrderState(OrderRequest) returns (OrderStateResponse);
  rpc CreateNewOrder(CreateOrderRequest) returns (CreateOrderResponse);
  rpc RejectOrder(RejectOrderRequest) returns (google.protobuf.Empty);
}

message OrderRequest{
  string orderId = 1;
}

message OrderResponse{
  repeated ProductItem products = 1;
}

message ProductItem{
  string orderId = 1;
  string name = 2;
  string description = 3;
  int64 count = 4;
  double pricePerItem = 5;
  double totalPrice = 6;
}

message CreateOrderRequest{
  repeated listing.v1.ShortProductItem products = 1;
}

message CreateOrderResponse{
  string orderId = 1;
}

message OrderStateResponse{
  OrderState state = 1;
}

message RejectOrderRequest{
  string orderId = 1;
  string reason = 2;
}

enum OrderState{
  CREATED = 0;
  WAIT_PAID = 1;
  PAID = 2;
  REJECTED = 3;
}